#!/bin/bash

# Don't use set -o pipefail with head/tail/etc!
set -o pipefail

if test $# -lt 1
then
    echo "Usage: $0 [ (option)... ] (filename.xml)..."
    echo ""
    exit 1
fi

XML_FILENAMES=""
IS_ERRORS=false
for ARG in $*
do
    # FUTURE check for "--option"...
    XML_FILENAME="$ARG"
    if test ! -f "$XML_FILENAME"
    then
	echo "ERROR No such XML file: $XML_FILENAME"
	IS_ERRORS=true
	continue
    fi

    NEW_XML_FILENAMES="$XML_FILENAMES $XML_FILENAME"
    XML_FILENAMES=$NEW_XML_FILENAMES
done

if test "$IS_ERRORS" = "true"
then
    exit 2
fi

for XML_FILENAME in $XML_FILENAMES
do
    cat "$XML_FILENAME" \
	| awk '
	       BEGIN {
	           state = "none";
		   npc_index = 0;
	       }

	       state == "npc" && $0 ~ /^.*<\/item>.*$/ {
	           state = "none";
		   gsub(/<\/item>.*$/, "", $0);
		   print "---"
                   print "#"
                   print "# Preliminary fields that describe this overall file:"
                   print "#"
                   print "kind: vibrantgames.ca/npc"
                   print "version: 0.0.2"
                   print ""
                   print "#"
                   print "# Information about who submitted the data, when, how, etc.:"
                   print "#"
                   print "metadata:"
                   print "  #"
                   print "  # A unique identified for this submission."
                   print "  # Eventually auto-generated."
                   print "  # For now, I suggest: convert the character name to lower case,"
                   print "  # and replace all spaces and punctuation with underscores (_)"
                   print "  #"
                   print "  id: " npcs[npc_index]["id"]
                   print ""
                   print "  #"
                   print "  # The name of the submitter (your name)."
                   print "  #"
                   print "  author: " "!!!"
                   print ""
                   print "  #"
                   print "  # Email address of the submitter."
                   print "  #"
                   print "  email: " "!!!"
                   print ""
                   print "  #"
                   print "  # Date the NPC was created."
                   print "  # Must be in ISO 8601 format."
                   print "  # You can include the time if you want."
                   print "  #"
                   print "  # E.g. 2021-12-31"
                   print "  #      2021-12-31 23:59:59"
                   print "  #"
                   print "  date: \"" npcs[npc_index]["date"] "\""
		   print ""
                   print "  #"
		   print "  # Arbitrary labels that are opaque to the system, only"
		   print "  # potentially useful to humans.  For example, the original"
		   print "  # WordPress id of a character (1234 etc)."
		   print "  #"
		   print "  # Optional."
		   print "  #"
		   print "  labels:"
		   print "  - wordpress_id: " npcs[npc_index]["wordpress_id"]
                   print ""
                   print "  #"
                   print "  # In future more metadata will likely be needed."
                   print "  # How the data was submitted, some kind of digital"
                   print "  # signature giving Vibrant Games license to basically"
                   print "  # use the content however it chooses, etc..."
                   print "  #"
                   print ""
                   print "#"
                   print "# The content:"
                   print "#"
                   print "npc:"
                   print "  #"
                   print "  # Full name of the NPC."
                   print "  #"
                   print "  # Required."
                   print "  # Max length: ..."
                   print "  #"
		   print "  name: " npcs[npc_index]["name"];
                   print ""
                   print "  #"
                   print "  # The NPC artwork."
                   print "  # Comment out this field if it does not yet exist."
                   print "  # The filename can include a RELATIVE path:"
                   print "  #     path/to/my/image.jpg"
                   print "  # But it CANNOT be an absolute path:"
                   print "  #     C:\path\to\my\image.jpg"
                   print "  # For now let us keep all images in one directory,"
                   print "  # at least until that becomes a scaling nightmare."
                   print "  #"
                   print "  image: " "!!!"
                   print ""
                   print "  #"
                   print "  # Race, class, etc."
                   print "  # The taupe block on the left of the page."
                   print "  #"
                   print "  traits:"
                   print ""
                   print "    #"
                   print "    # Ages (case insensitive):"
                   print "    #   - child"
                   print "    #   - adolescent"
                   print "    #   - young adult"
                   print "    #   - middle aged adult"
                   print "    #   - older adult"
                   print "    #   - elderly"
                   print "    #"
                   print "    # Required."
                   print "    #"
                   print "    age: " "!!!"
                   print ""
                   print "    #"
                   print "    # Races (case insensitive):"
                   print "    #   - dragonborn"
                   print "    #   - drow"
                   print "    #   - dwarf"
                   print "    #   - duergar"
                   print "    #   - elf"
                   print "    #   - gnome"
                   print "    #   - half-elf"
                   print "    #   - halfling"
                   print "    #   - half-orc"
                   print "    #   - human"
                   print "    #   - orc"
                   print "    #   - tiefling"
                   print "    #"
                   print "    # Any other race is allowed, too."
                   print "    #"
                   print "    # Required."
                   print "    # Max length: ..."
                   print "    #"
                   print "    race: " "!!!"
                   print ""
                   print "    #"
                   print "    # The sub-race can be anything."
                   print "    # For example, swamp gnome or red elf etc."
                   print "    #"
                   print "    # Optional.  Can be commented out."
                   print "    # Max length: ..."
                   print "    #"
                   print "    sub-race: " "!!!"
                   print ""
                   print "    #"
                   print "    # Pronouns (case insensitive):"
                   print "    # - he/him"
                   print "    # - she/her"
                   print "    # - they/them"
                   print "    #"
                   print "    # Required."
                   print "    #"
                   print "    pronouns: " "!!!"
                   print ""
                   print "    #"
                   print "    # Occupation(s)."
                   print "    #"
                   print "    # Required."
                   print "    # Max length per occupation: ..."
                   print "    #"
                   print "    occupation:"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print ""
                   print "    #"
                   print "    # D & D classes (case insensitive):"
                   print "    # - civilian"
                   print "    # - artificer"
                   print "    # - barbarian"
                   print "    # - bard"
                   print "    # - bloodhunter"
                   print "    # - cleric"
                   print "    # - druid"
                   print "    # - fighter"
                   print "    # - monk"
                   print "    # - paladin"
                   print "    # - ranger"
                   print "    # - rogue"
                   print "    # - shaman"
                   print "    # - sorcerer"
                   print "    # - warlock"
                   print "    # - wizard"
                   print "    #"
                   print "    # Required."
                   print "    #"
                   print "    class: " "!!!"
                   print ""
                   print "    #"
                   print "    # Class level."
                   print "    # 0 for civilian."
                   print "    #"
                   print "    # Required."
                   print "    # Integer."
                   print "    #"
                   print "    level: " "!!!"
                   print ""
                   print "    #"
                   print "    # Alignments (case insensitive):"
                   print "    # - lawful good"
                   print "    # - lawful neutral"
                   print "    # - lawful evil"
                   print "    # - neutral good"
                   print "    # - neutral"
                   print "    # - neutral evil"
                   print "    # - chaotic good"
                   print "    # - chaotic neutral"
                   print "    # - chaotic evil"
                   print "    #"
                   print "    # Required."
                   print "    #"
                   print "    alignment: " "!!!"
                   print ""
                   print "    #"
                   print "    # Alignment tendencies:"
                   print "    # same as alignment, can be 0 or more."
                   print "    #"
                   print "    # Optional."
                   print "    #"
                   print "    tendencies:"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print ""
                   print "    #"
                   print "    # Languages the character speaks"
                   print "    # (human, dwarvish, etc)."
                   print "    #"
                   print "    # We should use whatever the D & D language names"
                   print "    # are (dwarvish / dwarven / dwarfish / whatever)."
                   print "    #"
                   print "    # Anybody want to list the D & D languages here as examples?"
                   print "    #"
                   print "    # 0 o more.  (I.e. optional, but most characters speak at least 1.)"
                   print "    #"
                   print "    languages:"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print ""
                   print "    #"
                   print "    # Factions:"
                   print "    # These should be ids of factions (similar YAML file format, eventually)."
                   print "    # For example:"
                   print "    #"
                   print "    # factions:"
                   print "    # - thieves_guild_of_poliwood"
                   print "    # - union_of_seamstresses"
                   print "    # - cult_of_sky_anthologies"
                   print "    #"
                   print "    # Optional.  0 or more."
                   print "    #"
                   print "    factions:"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print ""
                   print "  improv:"
                   print ""
                   print "    #"
                   print "    # Introduction:"
                   print "    # A block of text the DM can read out to the party."
                   print "    # A hooded dwarf darts in front of your party and blows a loud, shrill whistle, splitting your ears, before he runs away laughing."
                   print "    #"
                   print "    # Required."
                   print "    # Max 120 characters."
                   print "    #"
                   print "    # Use this as a template:"
                   print "    #             |----------------------------------------------------------------------------------------------------------------------|"
                   print "    #"
                   print "    introduction: " "!!!"
                   print ""
                   print "    #"
                   print "    # Appearance: a brief description of the character skin, clothes, hair, eyes, etc."
                   print "    #"
                   print "    # Required."
                   print "    # Max 120 characters."
                   print "    #"
                   print "    # Use this as a template:"
                   print "    #             |----------------------------------------------------------------------------------------------------------------------|"
                   print "    #"
                   print "    appearance:   " "!!!"
                   print ""
                   print "    #"
                   print "    # Expressions: things the character says all the time, making their speech distinctive."
                   print "    # Like, oh my gods!"
                   print "    # Detritus!"
                   print "    # Whoah"
                   print "    # Silly goose"
                   print "    # etc."
                   print "    #"
                   print "    # Required."
                   print "    # Max 120 characters."
                   print "    #"
                   print "    # Use this as a template:"
                   print "    #             |----------------------------------------------------------------------------------------------------------------------|"
                   print "    #"
                   print "    expressions:  " "!!!"
                   print ""
                   print "    #"
                   print "    # Mannerisms: what does the character do with their hands?  And eyes, mouth, etc."
                   print "    # Do they tap their feet incessantly?  sniff their own underarms to figure out where the odour"
                   print "    # is coming from?  Etc."
                   print "    #"
                   print "    # Required."
                   print "    # Max 120 characters."
                   print "    #"
                   print "    # Use this as a template:"
                   print "    #             |----------------------------------------------------------------------------------------------------------------------|"
                   print "    #"
                   print "    mannerisms:   " "!!!"
                   print ""
                   print "  acting:"
                   print "    #"
                   print "    # Motivations:"
                   print "    #"
                   print "    # Required."
                   print "    # ???Maximum length???"
                   print "    #"
                   print "    motivations: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print ""
                   print "    #"
                   print "    # Passions:"
                   print "    #"
                   print "    # Required."
                   print "    # ???Maximum length???"
                   print "    #"
                   print "    passions: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print ""
                   print "    #"
                   print "    # Vulnerabilities:"
                   print "    #"
                   print "    # Required."
                   print "    # ???Maximum length???"
                   print "    #"
                   print "    vulnerabilities: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print ""
                   print "    #"
                   print "    # Secrets:"
                   print "    #"
                   print "    # Required."
                   print "    # ???Maximum length???"
                   print "    #"
                   print "    secrets: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print ""
                   print "  #"
                   print "  # The D & D stats block:"
                   print "  # All integers."
                   print "  #"
                   print "  stats:"
                   print "    armour-class: " "!!!"
                   print "    hit-points: " "!!!"
                   print "    speed: " "!!!"
                   print "    str: " "!!!"
                   print "    dex: " "!!!"
                   print "    con: " "!!!"
                   print "    int: " "!!!"
                   print "    wis: " "!!!"
                   print "    cha: " "!!!"
                   print ""
                   print "  #"
                   print "  # Special characteristics."
                   print "  #"
                   print "  # Each is:"
                   print "  # ???Optional???"
                   print "  # ???Max length???"
                   print "  #"
                   print "  specialties:"
                   print "    special-abilities: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print "    attacks: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print "    combat-tactics: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print "    special-equipment:"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print "    - " "!!!"
                   print ""
                   print "  profile:"
                   print ""
                   print "    #"
                   print "    # Background story:"
                   print "    # The long form character development."
                   print "    #"
                   print "    # Required."
                   print "    # No length limit for now."
                   print "    #"
                   print "    background-story: |"
                   print "      " "!!!"
                   print "      " "!!!"
                   print "      " "!!!"
                   print ""
                   print "    #"
                   print "    # Personality (or something like that):"
                   print "    # Expand on the introduction, appearance, expressions, mannerisms, etc."
                   print "    # without any length limits."
                   print "    #"
                   print "    # Required."
                   print "    # No length limit for now."
                   print "    #"
                   print "    personality: |"
                   print "      " "!!!"
                   print "      " "!!!"
		   print ""
		   print "  #"
		   print "  # Content that does not get displayed, but could be useful"
		   print "  # to humans.  Includes review comments, notes about what to"
		   print "  # do for the NPC art, or whatever else we need."
		   print "  #"
		   print "  # Optional."
		   print "  #"
		   print "  # uncategorized:"
	       }

	       state == "none" && $0 ~ /^.*<item>.*$/ {
	           state = "npc";
		   gsub(/^.*<item>/, "", $0);
		   npc_index ++;
	       }

	       state == "npc" && $0 ~ /^.*<title>.*<\/title>.*$/ {
	           npc_name = $0;
		   gsub(/^.*<title>/, "", npc_name);
		   gsub(/<\/title>.*$/, "", npc_name);
		   gsub(/^<!\[CDATA\[/, "", npc_name);
		   gsub(/\]\]>$/, "", npc_name);
		   npcs[npc_index]["name"] = npc_name;
	       }

	       state == "npc" && $0 ~ /^.*<wp:post_id>.*<\/wp:post_id>.*$/ {
	           npc_wordpress_id = $0;
		   gsub(/^.*<wp:post_id>/, "", npc_wordpress_id);
		   gsub(/<\/wp:post_id>.*$/, "", npc_wordpress_id);
		   gsub(/^<!\[CDATA\[/, "", npc_wordpress_id);
		   gsub(/\]\]>$/, "", npc_wordpress_id);
		   npcs[npc_index]["wordpress_id"] = npc_wordpress_id;
	       }

	       state == "npc" && $0 ~ /^.*<wp:post_date_gmt>.*<\/wp:post_date_gmt>.*$/ {
	           npc_date = $0;
		   gsub(/^.*<wp:post_date_gmt>/, "", npc_date);
		   gsub(/<\/wp:post_date_gmt>.*$/, "", npc_date);
		   gsub(/^<!\[CDATA\[/, "", npc_date);
		   gsub(/\]\]>$/, "", npc_date);
		   npcs[npc_index]["date"] = npc_date;
	       }

	       state == "npc" && $0 ~ /^.*<wp:post_name>.*<\/wp:post_name>.*$/ {
	           npc_id = $0;
		   gsub(/^.*<wp:post_name>/, "", npc_id);
		   gsub(/<\/wp:post_name>.*$/, "", npc_id);
		   gsub(/^<!\[CDATA\[/, "", npc_id);
		   gsub(/\]\]>$/, "", npc_id);
		   gsub(/-/, "_", npc_id);
		   npcs[npc_index]["id"] = npc_id;
	       }
              '
done

echo ""
echo "SUCCESS converting WordPress XML file(s) to YAML."
echo ""

exit 0


# 
# 	       state == "npc" && $0 ~ /^.*<!!!>.*<\/!!!>.*$/ {
# 	           npc_!!! = $0;
# 		   gsub(/^.*<!!!>/, "", npc_!!!);
# 		   gsub(/<\/!!!>.*$/, "", npc_!!!);
# 		   gsub(/^<!\[CDATA\[/, "", npc_!!!);
# 		   gsub(/\]\]>$/, "", npc_!!!);
# 		   npcs[npc_index]["!!!"] = npc_!!!;
# 	       }
