---
apiVersion: v1
kind: Namespace
metadata:
  name: www
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-v0
  namespace: www
  labels:
    app: www-v0

spec:
  selector:
    matchLabels:
      app: www-v0

  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 34%
      maxSurge: 1

  progressDeadlineSeconds: 600
  minReadySeconds: 0

  revisionHistoryLimit: 2

  template:
    metadata:
      labels:
        app: www-v0
    spec:
      containers:
      - name: main
        image: nginxinc/nginx-unprivileged:1.20.1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

      restartPolicy: Always
---
# Available as a LoadBalancer outside the cluster.
apiVersion: v1
kind: Service
metadata:
  name: www-v0-service
  namespace: www
spec:
  type: LoadBalancer
  selector:
    app: www-v0
  externalIPs:
    - 104.248.105.225
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
